application:
  verbose: 0
  logging: 0
  language: 'hi'


downloader: ## data loader
  link: 'https://www.youtube.com/watch?v=q8mcTibs-tI' # [*required](link, can be playlist, video link)
  output_dir_path: 'data/audiotospeech/raw/landing/hindi/audio'                  # output directory path
  mode: 'video'                           # can be [video, playlist, videolist]
  filename_prefix: 'amulya'        # filename prefix
  convert_to_wav: True                       # convert audio file to wav
  output_wav_dir: 'data/audiotospeech/raw/landing/hindi/audio'         # output directory path for converted wav
  raw_file_name: null
  duration: null
  title: null
  speaker_name: null
  audio_id: null
  cleaned_duration: null
  num_of_speakers: 1
  language: Hindi
  has_other_audio_signature: False
  type: 'audio'
  source: 'joshtalks2'
  experiment_use: False
  utterances_files_list: null
  source_url: null
  speaker_gender: 'Male'
  source_website: null
  experiment_name: null
  mother_tongue: null
  age_group: null
  recorded_state: null
  recorded_district: null
  recorded_place: null
  recorded_date: null
  purpose: null


