---
link: "https://www.youtube.com/watch?v=ruqMj-RQ_zA"
output_dir_path: "data/audiotospeech/raw/landing/hindi/audio"
mode: "video"
filename_prefix: "yey1"
convert_to_wav: true
output_wav_dir: "data/audiotospeech/raw/landing/hindi/audio"
raw_file_name: null
duration: null
title: null
speaker_name: null
audio_id: null
cleaned_duration: null
num_of_speakers: 1
language: "Hindi"
has_other_audio_signature: false
type: "audio"
source: "joshtalks2"
experiment_use: false
utterances_files_list: null
source_url: null
speaker_gender: "Male"
source_website: null
experiment_name: null
mother_tongue: null
age_group: null
recorded_state: null
recorded_district: null
recorded_place: null
recorded_date: null
purpose: null
mdoe: "video"
